#ifndef		__RecipeOffset_h__
#define		__RecipeOffset_h__

/**************************************************************
				 Recipe 관련 Structure : 미사용 Reserved
**************************************************************/

// LINK MAP
#define	MAX_RECIPE_ITEM					500	//1000

#define	MAX_ETCHING_BATH_RECIPE_ITEM	64
#define MAX_ETCHING_RINSE_OFFSET		9

#define	MAX_STRIP_BATH_RECIPE_ITEM		64
#define MAX_STRIP_RINSE_OFFSET			9

enum eModuleRecipeNo
{
	eCLN_RECIPE_NO		= 400,			// CLN & ETCH 같이 사용
	eCLN_LINE_TACT		= 401,			// CLN & ETCH 같이 사용
	eSTRIP_RECIPE_NO	= 900,	
	eSTRIP_LINE_TACT	= 901,
};

enum eEQPFCType
{
	ePFC_RB1_RBRUSH_USE				=	384,
	ePFC_RB1_RBRUSH1_SPINDIR		=	385,
	ePFC_RB1_RBRUSH1_SPEED			=	386,
	ePFC_WATERJET_USE				=	387,
	ePFC_RB1_BRUSH1_PRESS_GAP_UPPER	=	388,
	ePFC_RB1_BRUSH1_PRESS_GAP_LOWER	=	389,
	ePFC_RB1_BRUSH2_PRESS_GAP_UPPER	=	390,
	ePFC_RB1_BRUSH2_PRESS_GAP_LOWER	=	391,
	ePFC_RB1_BRUSH3_PRESS_GAP_UPPER	=	392,
	ePFC_RB1_BRUSH3_PRESS_GAP_LOWER	=	393,
	ePFC_RB1_BRUSH4_PRESS_GAP_UPPER	=	394,
	ePFC_RB1_BRUSH4_PRESS_GAP_LOWER	=	395,
	ePFC_RB1_BRUSH5_PRESS_GAP_UPPER	=	396,
	ePFC_RB1_BRUSH5_PRESS_GAP_LOWER	=	397,
	ePFC_RB1_BRUSH6_PRESS_GAP_UPPER	=	398,
	ePFC_RB1_BRUSH6_PRESS_GAP_LOWER	=	399,
	ePFC_RB1_BRUSH7_PRESS_GAP_UPPER	=	400,
	ePFC_RB1_BRUSH7_PRESS_GAP_LOWER	=	401,
	ePFC_RB1_BRUSH8_PRESS_GAP_UPPER	=	402,
	ePFC_RB1_BRUSH8_PRESS_GAP_LOWER	=	403,
	ePFC_R1_SPRAY_OPTION			=	453,
	ePFC_PROCESS_DATA_NUMBER		=	479,
	ePFC_TACT_TIME					=	480,
	ePFC_THROUGH_MODE				=	481,
	ePFC_TANK_SELECT				=	482,
	ePFC_PROCESS_SPEED				=	486,
	ePFC_UV_LAMP_USE				=	488,
	ePFC_UV_PROCESS_SPEED			=	489,
	ePFC_PLASMA_POWER				=	490,
	ePFC_PLASMA_USE					=	491,
	ePFC_PLASMA_PROCESS_SPEED		=	492,
	ePFC_PLASMA_N2					=	494,
	ePFC_PLASMA_CDA					=	495,
};

enum eEQEDGEType
{
	eEDGE_BRUSH_USE_UPPER			=	384,
	eEDGE_BRUSH_SPINDIR_UPPER		=	385,
	eEDGE_BRUSH_SPEED				=	386,
	eEDGE_RECIPE_NUMBER				=	479,
	eEDGE_GLASS_LENGTH				=	484,
	eEDGE_GLASS_WIDTH				=	485,
	eEDGE_PROCESS_SPEED				=	486,
	eEDGE_GLASS_SIZE				=	487,
};

enum eEQWRUType
{
	eWRU_PROCESS_DATA_NUMBER		=	479,
	eWRU_TACT_TIME					=	480,
	eWRU_NOZZLE_SPRAY_USE			=	493,
};

enum eEQLCPIType		// LC PI
{
	eLC_PI_PROCESS_DATA_NUMBER			=	0,
	eLC_PI_TACT_TIME					=	1,
	eLC_PI_AP01_USED					=	2,
	eLC_PI_AP01_OUT_DATA				=	3,
	eLC_PI_RB1_RBRUSH_USE				=	4,
	eLC_PI_RB1_RBRUSH1_SPEED			=	5,
	eLC_PI_RB1_RBRUSH1_SPINDIR			=	6,
	eLC_PI_RB1_BRUSH1_PRESS_GAP_UPPER	=	7,
	eLC_PI_RB1_BRUSH1_PRESS_GAP_LOWER	=	8,
	eLC_PI_RB1_BRUSH2_PRESS_GAP_UPPER	=	9,
	eLC_PI_RB1_BRUSH2_PRESS_GAP_LOWER	=	10,
	eLC_PI_RB1_BRUSH3_PRESS_GAP_UPPER	=	11,
	eLC_PI_RB1_BRUSH3_PRESS_GAP_LOWER	=	12,
	eLC_PI_RB1_BRUSH4_PRESS_GAP_UPPER	=	13,
	eLC_PI_RB1_BRUSH4_PRESS_GAP_LOWER	=	14,

	eLC_PI_RB_SPRAY_USED				=	15,	
	eLC_PI_R1_SPRAY_USED				=	16,
	eLC_PI_R2_SPRAY_USED				=	17,
	eLC_PI_R3_SPRAY_USED				=	18,

	eLC_PI_AP02_USED					=	19,
	eLC_PI_AP02_OUT_DATA				=	20,
	eLC_PI_EUV_LAMP_USED				=	21,
	eLC_PI_TURN_TABLE_ANGLE				=	22,
	eLC_PI_TANK_TEMP_SET				=	23,

	eLC_PI_CB01_CDA_FLOW_USED			=	24,
	eLC_PI_CB02_CDA_FLOW_USED			=	25,
	eLC_PI_TILT_CDA_FLOW_USED			=	26,
	eLC_PI_TURN_CDA_FLOW_USED			=	27,

	eLC_PI_CARRY_SPEED					=	28,
};

enum eEQLCODFType			//LC ODF			
{
	eLC_ODF_PROCESS_DATA_NUMBER			=	0,
	eLC_ODF_TACT_TIME					=	1,
	eLC_ODF_IPA_SPRAY_OPTION			=	2,
	eLC_ODF_R1_SPRAY_OPTION				=	3,
	eLC_ODF_R2_SPRAY_OPTION				=	4,
	eLC_ODF_RB1_RBRUSH_USE				=	5,
	eLC_ODF_RB1_RBRUSH1_SPEED			=	6,
	eLC_ODF_RB1_RBRUSH1_SPINDIR			=	7,
	eLC_ODF_RB1_BRUSH1_PRESS_GAP_LOWER	=	8,
	eLC_ODF_RB1_BRUSH2_PRESS_GAP_LOWER	=	9,
	eLC_ODF_R3_SPRAY_USE				=	10,
	eLC_ODF_ER_REGULATOR_USED			=	11,
	eLC_ODF_ER1_SET_VALUE				=	12,
	eLC_ODF_ER2_SET_VALUE				=	13,
	eLC_ODF_ER3_SET_VALUE				=	14,
	eLC_ODF_ER4_SET_VALUE				=	15,
	eLC_ODF_ER5_SET_VALUE				=	16,
	eLC_ODF_ER6_SET_VALUE				=	17,
	eLC_ODF_ER7_SET_VALUE				=	18,
	eLC_ODF_ER8_SET_VALUE				=	19,
	eLC_ODF_ER9_SET_VALUE				=	20,
	eLC_ODF_ER10_SET_VALUE				=	21,
	eLC_ODF_CARRY_SPEED					=	22,
};

enum eEQLCRWType		// LC Rework
{
	eLC_RW_PROCESS_DATA_NUMBER			=	0,
	eLC_RW_TACT_TIME					=	1,
	eLC_RW_CB_SPRAY_USED				=	2,
	eLC_RW_RB_SPRAY_USED				=	3,
	eLC_RW_RB1_RBRUSH_USE				=	4,
	eLC_RW_RB1_RBRUSH1_SPEED			=	5,
	eLC_RW_RB1_RBRUSH1_SPINDIR			=	6,
	eLC_RW_RB1_BRUSH1_PRESS_GAP_UPPER	=	7,
	eLC_RW_RB1_BRUSH1_PRESS_GAP_LOWER	=	8,
	eLC_RW_RB1_BRUSH2_PRESS_GAP_UPPER	=	9,
	eLC_RW_RB1_BRUSH2_PRESS_GAP_LOWER	=	10,
	eLC_RW_R1_SPRAY_USED				=	11,
	eLC_RW_R2_SPRAY_USED				=	12,
	eLC_RW_R3_SPRAY_USED				=	13,
	eLC_RW_TANK_TEMP_SET				=	14,
	eLC_RW_CARRY_SPEED					=	15,
};


enum eEQETCHType
{
	eETCH_B1_S1_Proc_Mode			=	0,
	eETCH_B1_S2_Proc_Mode			=	1,
	eETCH_B1_S3_Proc_Mode			=	2,
	eETCH_B1_S4_Proc_Mode			=	3,
	eETCH_B1_S5_Proc_Mode			=	4,
	eETCH_B1_S1_Proc_Time			=	5,
	eETCH_B1_S2_Proc_Time			=	6,
	eETCH_B1_S3_Proc_Time			=	7,
	eETCH_B1_S4_Proc_Time			=	8,
	eETCH_B1_S5_Proc_Time			=	9,
	eETCH_B1_S1_EPD_Alarm_WUL		=	10,
	eETCH_B1_S2_EPD_Alarm_WUL		=	11,
	eETCH_B1_S3_EPD_Alarm_WUL		=	12,
	eETCH_B1_S4_EPD_Alarm_WUL		=	13,
	eETCH_B1_S5_EPD_Alarm_WUL		=	14,
	eETCH_B1_S1_EPD_Alarm_SUL		=	15,
	eETCH_B1_S2_EPD_Alarm_SUL		=	16,
	eETCH_B1_S3_EPD_Alarm_SUL		=	17,
	eETCH_B1_S4_EPD_Alarm_SUL		=	18,
	eETCH_B1_S5_EPD_Alarm_SUL		=	19,
	eETCH_B1_S1_EPD_Alarm_SLL		=	20,
	eETCH_B1_S2_EPD_Alarm_SLL		=	21,
	eETCH_B1_S3_EPD_Alarm_SLL		=	22,
	eETCH_B1_S4_EPD_Alarm_SLL		=	23,
	eETCH_B1_S5_EPD_Alarm_SLL		=	24,
	eETCH_B1_S1_EPD_Alarm_WLL		=	25,
	eETCH_B1_S2_EPD_Alarm_WLL		=	26,
	eETCH_B1_S3_EPD_Alarm_WLL		=	27,
	eETCH_B1_S4_EPD_Alarm_WLL		=	28,
	eETCH_B1_S5_EPD_Alarm_WLL		=	29,
	eETCH_B1_S1_EPD_ADD_Percent		=	30,
	eETCH_B1_S2_EPD_ADD_Percent		=	31,
	eETCH_B1_S3_EPD_ADD_Percent		=	32,
	eETCH_B1_S4_EPD_ADD_Percent		=	33,
	eETCH_B1_S5_EPD_ADD_Percent		=	34,
	eETCH_B1_S1_EPD_ADD_Time		=	35,
	eETCH_B1_S2_EPD_ADD_Time		=	36,
	eETCH_B1_S3_EPD_ADD_Time		=	37,
	eETCH_B1_S4_EPD_ADD_Time		=	38,
	eETCH_B1_S5_EPD_ADD_Time		=	39,
	eETCH_B1_S1_EPD_Upper_Add_Time	=	40,
	eETCH_B1_S2_EPD_Upper_Add_Time	=	41,
	eETCH_B1_S3_EPD_Upper_Add_Time	=	42,
	eETCH_B1_S4_EPD_Upper_Add_Time	=	43,
	eETCH_B1_S5_EPD_Upper_Add_Time	=	44,
	eETCH_B1_S1_EPD_Lower_Add_Time	=	45,
	eETCH_B1_S2_EPD_Lower_Add_Time	=	46,
	eETCH_B1_S3_EPD_Lower_Add_Time	=	47,
	eETCH_B1_S4_EPD_Lower_Add_Time	=	48,
	eETCH_B1_S5_EPD_Lower_Add_Time	=	49,
	eETCH_B1_SPRAY_USED				=	55,
	eETCH_B1_INSHOWER_MODE_SELECT	=	56,
	eETCH_B1_PROC_OSCILLAT_MODE		=	57,

	eETCH_B2_S1_Proc_Mode			=	64,
	eETCH_B3_S1_Proc_Mode			=	128,
	eETCH_B4_S1_Proc_Mode			=	192,
	eETCH_B5_S1_Proc_Mode			=	256,
	eETCH_B6_S1_Proc_Mode			=	320,

	eETCH_R1_PROC_SETTIME			=	448,
	eETCH_R1_SPRAY_USED				=	450,
	eETCH_R1_INSHOWER_MODE_SELECT	=	451,
	eETCH_R1_SPRAY_MODE				=	452,
	eETCH_R1_SPRAY_OPTION			=	453,

	eETCH_R2_PROC_SETTIME			=	457,
	eETCH_R3_PROC_SETTIME			=	466,

	eETCH_PROCESS_DATA_NUMBER		=	479,
	eETCH_LINE_TACT					=	480,
	eETCH_THROUGH_MODE				=	481,
	eETCH_UV_LAMP_USE				=	488,

	eETCH_PLASMA_POWER				=	490,
	eETCH_PLASMA_USE				=	491,
	eETCH_PLASMA_PROCESS_SPEED		=	492,
	eETCH_PLASMA_N2					=	494,
	eETCH_PLASMA_CDA				=	495,
};

#endif	//RecipeOffset.H